
[versions]
# Build & SDK
agp = "8.13.2"
kotlin = "2.2.20"
compileSdk = "36"
targetSdk = "36"
minSdk = "24"
desugar-jdk-libs = "2.1.5"
multidex = "1.0.3"

# Kotlinx
kotlinx-collections-immutable = "0.4.0"

# AndroidX Core & UI
core-ktx = "1.17.0"
appcompat = "1.7.1"
constraintlayout = "2.2.1"
recyclerview = "1.4.0"
vectordrawable = "1.2.0"
webkit = "1.14.0"
viewpager2 = "1.1.0"
fragment-ktx = "1.8.9"

# AndroidX Lifecycle, Navigation, Paging
lifecycle = "2.10.0"
lifecycle-extensions = "2.2.0"
navigation = "2.9.6"
paging = "3.3.6"

# Coroutines
coroutines = "1.10.2"

# Compose
compose-bom = "2025.12.01"
coil-compose = "3.3.0"
activity-compose = "1.12.1"
material3 = "1.4.0"

# Play services
app-update = "2.1.0"
play-services-ads = "24.9.0"
play-services-location = "21.3.0"
play-services-auth = "21.4.0"

# Google, Firebase, Hilt
material = "1.13.0"
google-services = "4.4.4"
firebase-bom = "34.7.0"
firebase-crashlytics-gradle = "3.0.6"
firebase-config = "23.0.1"
firebase-database = "22.0.1"
firebase-inappmessaging = "21.0.2"
firebase-messaging = "25.0.1"
hilt = "2.57.2"

# Network & Serialization
retrofit = "3.0.0"
okhttp = "5.3.2"
kotlinx-serialization = "1.9.0"
gson = "2.13.2"

# Other 3rd party
glide = "5.0.5"
lottie = "6.7.1"
flexbox = "3.0.0"
simple-rating-bar = "1.5.1"
hashtag-view = "1.3.1"
tedimagepicker = "1.6.1"

# Map & Social Login
naver-map = "3.21.0"
kakao-login = "2.12.0"

# Testing
junit = "4.13.2"
androidx-test-ext-junit = "1.3.0"
espresso-core = "3.7.0"

[libraries]
# --- Kotlin & Coroutines ---
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin" }
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutines" }
kotlinx-collections-immutable = { group = "org.jetbrains.kotlinx", name = "kotlinx-collections-immutable", version.ref = "kotlinx-collections-immutable"}

# --- AndroidX Core & UI ---
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "recyclerview" }
androidx-vectordrawable = { group = "androidx.vectordrawable", name = "vectordrawable", version.ref = "vectordrawable" }
androidx-webkit = { group = "androidx.webkit", name = "webkit", version.ref = "webkit" }
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "viewpager2" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment-ktx" }

# --- Lifecycle, Navigation, Paging ---
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
androidx-lifecycle-livedata-ktx = { group = "androidx.lifecycle", name = "lifecycle-livedata-ktx", version.ref = "lifecycle" }
androidx-lifecycle-extensions = { group = "androidx.lifecycle", name = "lifecycle-extensions", version.ref = "lifecycle-extensions" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }
androidx-paging-common-ktx = { group = "androidx.paging", name = "paging-common-ktx", version.ref = "paging" }
androidx-paging-runtime-ktx = { group = "androidx.paging", name = "paging-runtime-ktx", version.ref = "paging" }

# --- Compose ---
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-activity-compose = {group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose"}
coil-compose = { group = "io.coil-kt.coil3", name = "coil-compose", version.ref = "coil-compose" }
coil-network-okhttp = { group = "io.coil-kt.coil3", name = "coil-network-okhttp", version.ref = "coil-compose" }

# --- Hilt (DI) ---
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# --- Network & Serialization ---
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { group = "com.jakewharton.retrofit", name = "retrofit2-kotlinx-serialization-converter", version = "1.0.0" }
retrofit-converter-moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "retrofit" }
okhttp-logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "okhttp" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }

# --- Firebase ---
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics" }
firebase-crashlytics = { group = "com.google.firebase", name = "firebase-crashlytics" }
firebase-config = { group = "com.google.firebase", name = "firebase-config", version.ref = "firebase-config" }
firebase-database = { group = "com.google.firebase", name = "firebase-database", version.ref = "firebase-database" }
firebase-inappmessaging-display-ktx = { group = "com.google.firebase", name = "firebase-inappmessaging-display-ktx", version.ref = "firebase-inappmessaging" }
firebase-messaging = { group = "com.google.firebase", name = "firebase-messaging", version.ref = "firebase-messaging"}

# --- Other Libraries ---
glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }
flexbox = { group = "com.google.android.flexbox", name = "flexbox", version.ref = "flexbox" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugar-jdk-libs" }
multidex = { group = "com.android.support", name = "multidex", version.ref = "multidex" }
simple-rating-bar = { group = "com.github.ome450901", name = "SimpleRatingBar", version.ref = "simple-rating-bar" }
hashtag-view = { group = "com.github.greenfrvr", name = "hashtag-view", version.ref = "hashtag-view" }
tedimagepicker = { group = "io.github.ParkSangGwon", name = "tedimagepicker", version.ref = "tedimagepicker" }

# --- Map & Social Login ---
naver-map = { group = "com.naver.maps", name = "map-sdk", version.ref = "naver-map" }
kakao-login = { group = "com.kakao.sdk", name = "v2-all", version.ref = "kakao-login" }

# --- Play Services ---
play-app-update-ktx = { group = "com.google.android.play", name = "app-update-ktx", version.ref = "app-update" }
play-services-ads = { group = "com.google.android.gms", name = "play-services-ads", version.ref = "play-services-ads" }
play-services-location = { group = "com.google.android.gms", name = "play-services-location", version.ref = "play-services-location" }
play-services-auth = { group = "com.google.android.gms", name = "play-services-auth", version.ref = "play-services-auth" }

# --- Testing ---
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

[bundles]
androidx-ui = [
    "androidx-core-ktx",
    "androidx-appcompat",
    "google-material",
    "androidx-constraintlayout",
    "androidx-recyclerview",
    "androidx-fragment-ktx",
    "androidx-activity-compose"
]
androidx-lifecycle = [
    "androidx-lifecycle-viewmodel-ktx",
    "androidx-lifecycle-livedata-ktx"
]
androidx-navigation = [
    "androidx-navigation-fragment-ktx",
    "androidx-navigation-ui-ktx"
]
compose = [
    "androidx-compose-ui",
    "androidx-compose-material3",
    "androidx-compose-ui-tooling-preview",
    "kotlinx-collections-immutable"
]
coil-compose = [
    "coil-compose",
    "coil-network-okhttp"
]
retrofit = [
    "retrofit",
    "retrofit-converter-kotlinx-serialization",
    "retrofit-converter-moshi",
    "okhttp-logging-interceptor"
]
paging = [
    "androidx-paging-common-ktx",
    "androidx-paging-runtime-ktx"
]
testing = [
    "junit",
    "androidx-test-ext-junit",
    "espresso-core"
]

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "google-services" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "firebase-crashlytics-gradle" }
